// EventSourceManager.swift
// Manages the CGEventSource used for creating synthetic keyboard events.
// The source's stateID is used for self-event detection to prevent infinite loops.

import Cocoa

/// Owns the CGEventSource used by KeySender to create synthetic events.
/// The source's stateID lets the event tap callback distinguish our synthetic
/// events from real user keystrokes.
final class EventSourceManager {

    /// The event source used for all synthetic events.
    /// Created with `.privateState` so it has a unique stateID.
    let source: CGEventSource

    /// The stateID of our source. Events we create will carry this ID,
    /// letting the callback detect and skip them.
    let stateID: Int64

    init?() {
        guard let src = CGEventSource(stateID: .privateState) else {
            return nil
        }
        self.source = src
        self.stateID = Int64(src.sourceStateID.rawValue)

        // Prevent our synthetic keystrokes from generating additional system events
        // like key repeat or accessibility notifications.
        src.localEventsSuppressionInterval = 0.0
    }

    /// Check if a CGEvent was generated by us (i.e., is a synthetic event).
    func isSelfGenerated(_ event: CGEvent) -> Bool {
        let eventSourceID = event.getIntegerValueField(.eventSourceStateID)
        return eventSourceID == stateID
    }
}
